### ISSUE TITLE
remove #!/usr/bin/python

### ISSUE THREAD

**Issue by DanHickstein** [DanHickstein/pyBASEX#6]
@rth included the shebang: #!/usr/bin/python at the top of all the scripts. Am I correct in thinking that this is not really necessary for the main BASEX functions, since they will be installed and called from python? It might be a good idea for the examples, but still, I think that #!/usr/bin/env python will automatically find the first python distribution on the users path, which is probably the desired behavior. For example, on my system, I am using the anaconda python distribution, and /usr/bin/python uses the old version that came with my computer. I propose to remove the shebang from the functions. Sound good?

**Comment by rth** [comment]
@DanHickstein  You are right, that line is not necessary, is not platform independent and should be removed. Sorry about that.

**Comment by DanHickstein** [comment]
Sounds good! I removed the line from the files.
